server:
  port: 9090

spring:
  thymeleaf:
    cache: 'false'
    content-type: text/html
    enabled: 'true'
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    # mysql配置
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/rainbow-seckill?characterEncoding=utf-8&useSSL=false

    # Druid配置
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #  CharacterEncodingFilter 配置
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# mybatis配置
mybatis:
    type-aliases-package: com.jhon.rain.entity
    mapper-locations: classpath:com/jhon/rain/dao/*.xml
    configuration:
      default-fetch-size: 1000
      default-statement-timeout: 3000

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: false # 如果为true则，当前页大于总的页数时，默认去最后一页数据，如果为0或者负数，则默认取第一页
  support-methods-arguments: true
  params: count=countSql

#redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
  password: jhonrain
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
